language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
install: 
  - 'pip install -r requirements.txt --use-mirrors'
 
before_script:
  - wget http://googleappengine.googlecode.com/files/google_appengine_1.8.0.zip -nv
  - unzip -q google_appengine_1.8.0.zip

script:  python country.py test
