language: python

python:
  - "2.7"
  
install: 
  - 'pip install -r requirements.txt --use-mirrors'
  
env:
  global:
    - APPENGINE_SDK_VERSION=1.8.8 
    
before_script:
  - wget http://googleappengine.googlecode.com/files/google_appengine_$APPENGINE_SDK_VERSION.zip -nv
  - unzip -q google_appengine_$APPENGINE_SDK_VERSION.zip

script:  python country.py test
